# Basic makefile rules

PREFIX ?= /usr/local

ifdef V
  VERBOSE:= $(V)
else
  VERBOSE:= 0
endif

ifeq ($(VERBOSE),1)
define Q
  $(2)
endef
else
define Q
  @/bin/echo -e "	[$1]\t$(3)"
  @$(2)
endef
endif

obj/%.o : src/%.c src/include/libocxl.h src/libocxl_internal.h | obj
	$(call Q,CC, $(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<, $@)

testobj/%.o : src/%.c src/include/libocxl.h src/libocxl_internal.h | testobj
	$(call Q,CC, $(CC) $(CPPFLAGS) $(TESTCFLAGS) -c -o $@ $<, $@)

testobj/%.o-test : unittests/%.c testobj/libocxl.a
	$(call Q,CC, $(CC) $(CPPFLAGS) $(TESTCFLAGS) -c -o $@ $<, $@)

datadir    = $(PREFIX)/share
includedir = $(PREFIX)/include
mandir     = $(datadir)/man
libdir = $(PREFIX)/lib64
